_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
architecture:
    value: UNet
batch_size:
    value: 16
criterion:
    value: MSELoss
learning_rate:
    value: 0.01
lr_scheduler:
    value: ReduceLROnPlateau
min_delta:
    value: 1e-05
name:
    value: Leading-16_tform_c
patience:
    value: 5
scheduler_params:
    value:
        factor: 0.1
        min_lr: 1e-06
        mode: min
        patience: 5
transforms:
    value: []
weight_decay:
    value: 0.01
