_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
architecture:
    value: UNet
batch_size:
    value: 16
criterion:
    value: undef
learning_rate:
    value: 0.002
name:
    value: rand_h_v_rot_model_MSE
weight_decay:
    value: 0.01
