_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 24
                - 55
            "4": 3.12.7
            "5": 0.19.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
architecture:
    value: UNet
batch_size:
    value: 16
criterion:
    value: MSELoss
learning_rate:
    value: 0.002
lr_scheduler:
    value: type
min_delta:
    value: 1e-06
name:
    value: TEST_reduce_lr_on_plateau
patience:
    value: 10
weight_decay:
    value: 0.01
